<?php
/**
* Pacific NM (https://www.pacificnm.com)
*
* @link      https://github.com/pacificnm/pnm for the canonical source repository
* @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
* @license
*/
?>
<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header with-border">
				<h3 class="box-title">
					<i class="<?php echo $this->layout()->pageIcon; ?>" aria-hidden="true"></i>
					<?php echo $this->translate($this->layout()->pageTitle); ?> 
					<small><?php echo $this->translate("View"); ?></small>
				</h3>
				<div class="box-tools">
					<?php if($this->entity->getCategoryLevel() <= 4): ?>
					<a href="<?php echo $this->url('category-create', array(), array('query' => array('categoryLevel' => $this->entity->getCategoryLevel(), 'categoryParentId' => $this->entity->getCategoryId(), 'categoryRootId' => $this->entity->getCategoryRootId()))); ?>" title="<?php echo $this->translate('New'); ?>" class="btn btn-box-tool">
						<i class="fa fa-plus" aria-hidden="true"></i>
						<?php echo $this->translate("New"); ?>
					</a>
					<?php endif;?>
				
					<?php echo $this->deleteButton("category-delete", array("id" => $this->entity->getCategoryId())); ?>
					
					<?php echo $this->updateButton("category-update", array("id" => $this->entity->getCategoryId())); ?>
				</div>
			</div>
			<div class="box-body box-profile">
                <h3 class="profile-username text-center">
                	<?php echo $this->entity->getCategoryName(); ?>
                </h3>
                <p class="text-muted text-center"></p>
                <ul class="list-group list-group-unbordered">
                    <li class="list-group-item">
                    	<b><?php echo $this->translate("Category Id"); ?>: </b>
                    	<?php echo $this->entity->getCategoryId(); ?>
                    </li>
                    <li class="list-group-item">
                    	<b><?php echo $this->translate("Category Type"); ?>: </b>
                    	<a href="<?php echo $this->url('category-type-view', array('id' => $this->entity->getCategoryTypeId())); ?>" 
                    		title="<?php echo $this->entity->getCategoryTypeEntity()->getCategoryTypeName(); ?>">
                    		<?php echo $this->entity->getCategoryTypeEntity()->getCategoryTypeName(); ?>
                    	</a>
                    </li>
                     <li class="list-group-item">
                    	<b><?php echo $this->translate("Category Name"); ?>: </b>
                    	<?php echo $this->entity->getCategoryName(); ?>
                    </li>
                    <li class="list-group-item">
                    	<b><?php echo $this->translate("Category Parent"); ?>: </b>
                    	<?php if($this->entity->getCategoryParentId() == 0): ?>
                    	<?php echo $this->translate("Root Category"); ?>
                    	<?php else: ?>
                    	<a href="<?php echo $this->url('category-view', array("id" => $this->entity->getCategoryParentId())); ?>" title="<?php echo $entity->getCategoryParentEntity()->getCategoryParentName(); ?>">
							<?php echo $this->entity->getCategoryParentEntity()->getCategoryParentName(); ?>
						</a
                    	<?php endif; ?>
                    </li>
                    
                   
                    <li class="list-group-item">
                    	<b><?php echo $this->translate("Category Slug"); ?>: </b>
                    	<?php echo $this->entity->getCategorySlug(); ?>
                    </li>
                    <li class="list-group-item">
                    	<b><?php echo $this->translate("Category Level"); ?>: </b>
                    	<?php echo $this->entity->getCategoryLevel(); ?>
                    </li>
                    <li class="list-group-item">
                    	<b><?php echo $this->translate("Category Active"); ?>: </b>
                    	<?php echo $this->entity->getCategoryActive(); ?>
                    </li>
                </ul>
            </div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header with-border">
				<h3 class="box-title">
					<i class="<?php echo $this->layout()->pageIcon; ?>" aria-hidden="true"></i>
					<?php echo $this->translate("Category Attributes"); ?>
				</h3>
				<div class="box-tools">
					<?php echo $this->createButton('category-attribute-value-create', array('categoryId' => $this->entity->getCategoryId())); ?>
				</div>
			</div>
			<?php if($this->attributeValueEntitys->count() == 0): ?>
			<div class="box-body">
				<div class="alert alert-info">
					<i class="fa fa-info-circle"></i> <?php echo $this->translate(""); ?>
				</div>
			</div>
			<?php else: ?>
			<div class="box-body no-padding">
				<div class="row">
					<div class="col-xs-12">
						<table class="table table-bordered table-hover table-striped table-condensed">
							<thead>
								<tr>
									<th class="col-sm-2"><?php echo $this->translate("Attribute"); ?></th>
									<th><?php echo $this->translate("Value"); ?></th>
								</tr>
							</thead>
							<tbody>
							<?php foreach($this->attributeValueEntitys as $attributeValueEntity): ?>
								<tr>
									<td><?php echo $attributeValueEntity->getCategoryAttributeEntity()->getCategoryAttributeName(); ?></td>
									<td>
										<a href="<?php echo $this->url(); ?>" title="<?php echo $this->translate("View Attribute"); ?>">
										<?php if($attributeValueEntity->getCategoryAttributeEntity()->getCategoryAttributeType() == 'Boolean'): ?>
											<?php echo ($attributeValueEntity->getCategoryAttributeValue() == 1 ? $this->translate("Yes") : $this->translate("No")); ?>
										<?php else: ?>
											<?php echo $attributeValueEntity->getCategoryAttributeValue(); ?>
										<?php endif;?>
										</a>
									</td>
								</tr>
							<?php endforeach;?>
							</tbody>
						</table>
					</div>
				</div>
			</div>
			<?php endif; ?>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header with-border">
				<h3 class="box-title">
					<i class="<?php echo $this->layout()->pageIcon; ?>" aria-hidden="true"></i>
					<?php echo $this->translate("Child Categories"); ?>
					<small><?php echo $this->translate("Page"); ?>: <?php echo $this->page; ?></small>
				</h3>
				<div class="box-tools">
					<?php echo $this->searchButton("category-search"); ?></div>
			</div> 
            <?php if($this->paginator->count() == 0): ?>
			<div class="box-body">
				<div class="alert alert-info">
					<p>
						<i class="fa fa-info-circle" aria-hidden="true"></i> 
						<?php echo $this->translate("No entities found"); ?>
					</p>
				</div>
			</div>
			<?php else: ?>
			<div class="box-body no-padding">
				<div class="row">
					<div class="col-xs-12">
						<table class="table table-bordered table-hover table-striped table-condensed">
							<thead>
								<tr>
                                    <th><?php echo $this->translate("Category Id"); ?></th>
                                    <th><?php echo $this->translate("Name"); ?></th>
                                    <th><?php echo $this->translate("Parent"); ?>
                                    <th><?php echo $this->translate("Slug"); ?></th>
                                    <th><?php echo $this->translate("Level"); ?></th>
                                    <th><?php echo $this->translate("Active"); ?></th>
                                    
                                </tr>
							</thead>
							<tbody>
							<?php foreach($this->paginator as $entity): ?>
								<tr>
									<td><?php echo $entity->getCategoryId(); ?></td>
									<td><a href="<?php echo $this->url('category-view', array('id' => $entity->getCategoryId())); ?>" title="<?php echo $entity->getCategoryName(); ?>">
											<?php echo $entity->getCategoryName(); ?>
										</a>
									</td>
									<td>
										<?php if($entity->getCategoryParentId() == 0): ?>
										<?php echo $this->translate("Root Category"); ?>
										<?php else:?>
										<a href="<?php echo $this->url('category-view', array("id" => $entity->getCategoryParentId())); ?>" title="<?php echo $entity->getCategoryParentEntity()->getCategoryParentName(); ?>">
											<?php echo $entity->getCategoryParentEntity()->getCategoryParentName(); ?>
										</a>
										<?php endif; ?>
									</td>
									<td><?php echo $entity->getCategorySlug(); ?></td>
									<td><?php echo $entity->getCategoryLevel(); ?></td>
									<td><?php echo ($entity->getCategoryActive() == 1 ? $this->translate("Yes") : $this->translate("No")); ?></td>
                                </tr>
                            <?php endforeach; ?>
							</tbody>
						</table>
					</div>
				</div>
				
				<div class="row">
					<div class="col-xs-12 text-center">
						<?php echo $this->Paginator(
							$this->itemCountPerPage, 
							$this->itemCount, 
							$this->pageCount, 
                            $this->page, 
                            $this->routeParams,
                            $this->queryParams);
                        ?>
					</div>
				</div>
			</div>
			<?php endif;?>
		</div>
	</div>
</div>

<?php echo $this->categorySearchForm($this->queryParams); ?>   