<?php
/**
* Pacific NM (https://www.pacificnm.com)
*
* @link      https://github.com/pacificnm/pnm for the canonical source repository
* @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
* @license
*/
?>
<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header with-border">
				<h3 class="box-title">
					<i class="<?php echo $this->layout()->pageIcon; ?>" aria-hidden="true"></i>
					<?php echo $this->translate($this->layout()->pageTitle); ?> 
					<small><?php echo $this->translate("Page"); ?>: <?php echo $this->page; ?></small>
				</h3>
				<div class="box-tools">
					<a href="<?php echo $this->url('category-type-index'); ?>" 
						title="<?php echo $this->translate("Types"); ?>" class="btn-box-tool">
						<i class="fa fa-gear"></i>
						<?php echo $this->translate("Types"); ?>
					</a>
					
					<a href="<?php echo $this->url('category-attribute-index'); ?>" 
						title="<?php echo $this->translate("Attributes"); ?>" class="btn-box-tool">
						<i class="fa fa-gear"></i>
						<?php echo $this->translate("Attributes"); ?>
					</a>
					
					<?php echo $this->searchButton("category-search"); ?>
					
					<?php echo $this->createButton("category-create"); ?>
				</div>
			</div> 
            <?php if($this->paginator->count() == 0): ?>
			<div class="box-body">
				<div class="alert alert-info">
					<p>
						<i class="fa fa-info-circle" aria-hidden="true"></i> 
						<?php echo $this->translate("No entities found"); ?>
					</p>
				</div>
			</div>
			<?php else: ?>
			<div class="box-body  no-padding">
				<div class="row">
					<div class="col-xs-12">
						<table class="table table-bordered table-hover table-striped table-condensed">
							<thead>
								<tr>
                                    <th><?php echo $this->translate("Category Id"); ?></th>
                                    <th><?php echo $this->translate("Type"); ?></th>
                                    <th><?php echo $this->translate("Name"); ?></th>
                                    <th><?php echo $this->translate("Parent"); ?>
                                    <th><?php echo $this->translate("Slug"); ?></th>
                                    <th><?php echo $this->translate("Level"); ?></th>
                                    <th><?php echo $this->translate("Active"); ?></th>
                                    
                                </tr>
							</thead>
							<tbody>
							<?php foreach($this->paginator as $entity): ?>
								<tr>
									<td><?php echo $entity->getCategoryId(); ?></td>
									<td>
										<a href="<?php echo $this->url('category-type-view', array('id' => $entity->getCategoryTypeId())); ?>" title="<?php echo $entity->getCategoryTypeEntity()->getCategoryTypeName();?>">
											<?php echo $entity->getCategoryTypeEntity()->getCategoryTypeName();?>
										</a>
									</td>
									<td><a href="<?php echo $this->url('category-view', array('id' => $entity->getCategoryId())); ?>" title="<?php echo $entity->getCategoryName(); ?>">
											<?php echo $entity->getCategoryName(); ?>
										</a>
									</td>
									<td>
										<?php if($entity->getCategoryParentId() == 0): ?>
										<?php echo $this->translate("Root Category"); ?>
										<?php else:?>
										<a href="<?php echo $this->url('category-view', array("id" => $entity->getCategoryParentId())); ?>" title="<?php echo $entity->getCategoryParentEntity()->getCategoryParentName(); ?>">
											<?php echo $entity->getCategoryParentEntity()->getCategoryParentName(); ?>
										</a>
										<?php endif; ?>
									</td>
									<td><?php echo $entity->getCategorySlug(); ?></td>
									<td><?php echo $entity->getCategoryLevel(); ?></td>
									<td><?php echo ($entity->getCategoryActive() == 1 ? $this->translate("Yes") : $this->translate("No")); ?></td>
                                </tr>
                            <?php endforeach; ?>
							</tbody>
						</table>
					</div>
				</div>
				
				<div class="row">
					<div class="col-xs-12 text-center">
						<?php echo $this->Paginator(
							$this->itemCountPerPage, 
							$this->itemCount, 
							$this->pageCount, 
                            $this->page, 
                            $this->routeParams,
                            $this->queryParams);
                        ?>
					</div>
				</div>
			</div>
			<?php endif;?>
		</div>
	</div>
</div>


<?php echo $this->categorySearchForm($this->queryParams); ?>